### ISSUE TITLE
Changes to .rtorrent.rc not persistent

### ISSUE THREAD

**Issue by CaptInsano** [nuimk/rutorrent#1]
My setup is as follows:

/usr/bin/docker run -d --name="rutorrent" --net="bridge" -e TZ="Europe/London" -p 8089:80/tcp -p 45566:45566/tcp -p 9527:9527/udp -v "/mnt/cache/Docker/AppData/rTorrent/":"/torrent/":rw nuimk/rutorrent

When I make changes to rtorrent from rutorrent eg: Changing Ports, the settings are not persistent. 

If I stop and restart the container all settings return to the defaults.

Is there anything that can be done to allow changes to rTorrent settings?

Thanks for you work!

![capture](https://cloud.githubusercontent.com/assets/332478/6587208/4ed4cb08-c779-11e4-9827-51c8ffd17b0f.PNG)

**Comment by nui** [comment]
AFAIK, rtorrent doesn't save settings back to it .rtorrent.rc file. You may have to edit .rtorrent.rc manually.

**Comment by CaptInsano** [comment]
Ah OK, thanks for that!

I thought ruTorrent could change .rtorrent.rc.
